site_name: Nubomedia Documentation
pages:
- ['index.md', 'Get Started', 'Get Started']
- ['openbaton-overview.md', 'Get Started', 'Get Started with Openbaton']
- ['nubomedia-overview.md', 'Get Started', 'Get Started with Nubomedia']
- ['nubomedia-installation.md', 'Installation', 'Install Nubomedia']
- ['openbaton-installation.md', 'Installation', 'Install Openbaton']
- ['nfvo-installation.md', 'Installation', 'Install NFVO']
- ['emm-installation.md', 'Installation', 'Install MS-VNFM/EMM']
- ['crvnfm-installation.md', 'Installation', 'Install CR-VNFM']
- ['paas-installation.md', 'Installation', 'Install PaaS API']
- ['cm-installation.md', 'Installation', 'Install Connectivity Manager']
- ['use-it.md', 'Use it', 'Use it']
- ['cma-use-it.md', 'Use it', 'Use the Connectivity Manager Agent']
google_analytics: ['UA-68429895-1', 'openbaton.github.io']
theme: readthedocs
theme_dir: 'custom_theme'

